import { packages as rawPackages } from '../../data/packages'
import { stays as rawStays } from '../../data/stays'
import { vehicles as rawVehicles } from '../../data/vehicles'
import { categories as rawCategories } from '../../data/categories'
import { experiences as rawExperiences } from '../../data/experiences'
import { testimonials as rawTestimonials } from '../../data/testimonials'
import { normalizeHotelName } from '../normalization/hotel'
import { normalizeNumberPlate } from '../normalization/vehicle'
import type { Package, Hotel, Vehicle, Category, Experience, Testimonial, ChatKnowledge, SiteSettings } from '../../types/domain'

const packageDetails: Record<string, Partial<Package>> = {
  'munnar-escape': {
    nights: 2,
    shortDescription: 'Lose yourself in rolling tea gardens, cool mountain air, and the timeless beauty of Kerala\'s crown jewel.',
    coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80&auto=format',
    gallery: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80&auto=format',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80&auto=format',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80&auto=format',
    ],
    hotelIds: ['valley-view-homestay'],
    vehicleIds: ['innova-crysta', 'swift-dzire'],
    inclusions: [
      '2 Nights accommodation in a boutique valley-view resort',
      'Daily breakfast and authentic chef-curated mountain dinner',
      'Dedicated private AC sedan with experienced mountain chauffeur',
      'Guided walk through heritage Lockhart tea plantation',
      'Eravikulam National Park safari entry coordination',
      'All toll gates, parking charges, and driver allowances',
    ],
    exclusions: [
      'Airfare or train tickets to / from Kochi',
      'Lunches and personal beverage expenses',
      'Speed-boating tickets at Mattupetty and optional zip-lining',
      'Anything not explicitly mentioned under inclusions',
    ],
    importantInformation: [
      'Carry warm fleece jackets as evening and early morning temperatures drop significantly.',
      'Original photo identification is mandatory for all travelers at hotel check-in and park safari gates.',
      'Complimentary pickup is provided from Cochin International Airport (COK) or Aluva Railway Station.',
      'Kolukkumalai jeep safaris are weather-dependent and organized upon early morning request.',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival & Journey to the Mist-Covered Hills',
        description: 'Begin your scenic ascent from Kochi up the Western Ghats highway. Stop to photograph the roaring Cheeyappara and Valara waterfalls amidst verdant spice plantations. Arrive in Munnar, check into your panoramic hillside resort, and enjoy an evening orientation walk around Munnar town market.',
        locations: ['Kochi', 'Cheeyappara Waterfalls', 'Munnar Valley'],
        activities: ['Scenic Western Ghats mountain drive', 'Cheeyappara waterfall photography stop', 'Resort check-in with cardamom welcome tea', 'Evening spice and artisan chocolate market walk'],
        meals: ['Dinner'],
        accommodation: 'Valley View Hillside Resort',
        travelInfo: 'Private AC transfer (~130 km / 4 hours from Kochi)',
        images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80&auto=format'],
      },
      {
        day: 2,
        title: 'Eravikulam Wildlife Safari & Mattupetty Waters',
        description: 'Set out on an early morning safari into Eravikulam National Park, home to the endangered Nilgiri Tahr against the majestic backdrop of Anamudi peak. Afterwards, visit Mattupetty Dam, enjoy boating on the reservoir, shout into Echo Point, and take a guided walk through Lockhart Tea Factory.',
        locations: ['Eravikulam National Park', 'Mattupetty Dam', 'Echo Point', 'Tea Factory'],
        activities: ['Nilgiri Tahr wildlife spotting safari', 'Mattupetty Dam lakeside speed-boating', 'Acoustic echoes at Echo Point', 'Tea processing tour & leaf grading masterclass'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Valley View Hillside Resort',
        travelInfo: 'Full-day private vehicle sightseeing (~50 km local circuit)',
        images: ['https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80&auto=format'],
      },
      {
        day: 3,
        title: 'Top Station Cloud Panorama & Return Journey',
        description: 'Wake up early to witness a breathtaking sunrise above the clouds at Top Station overlooking the neighboring Tamil Nadu plains. Explore Pothamedu Viewpoint for final panoramic photographs before descending back to Kochi with lasting highland memories.',
        locations: ['Top Station', 'Pothamedu Viewpoint', 'Kochi Airport'],
        activities: ['Sunrise above the clouds at Top Station', 'Panoramic valley viewpoint photoshoot', 'Fresh spices and high-grown tea shopping', 'Return drop-off transfer to Kochi'],
        meals: ['Breakfast'],
        travelInfo: 'Return descent transfer to Kochi (~130 km / 4 hours)',
      },
    ],
  },
  'coorg-trails': {
    nights: 3,
    shortDescription: 'Step into the Scotland of India — emerald coffee estates, ancient abbeys, and cascading waterfalls await.',
    coverImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80&auto=format',
    gallery: [
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80&auto=format',
      'https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=800&q=80&auto=format',
    ],
    hotelIds: ['coorg-bungalow'],
    vehicleIds: ['innova-crysta', 'fortuner'],
    inclusions: [
      '3 Nights accommodation in a heritage coffee plantation estate',
      'Daily estate breakfast and traditional Kodava dinner spread',
      'Private chauffeur-driven cab for all sightseeing & transfers',
      'Guided coffee and black pepper bean-to-cup plantation tour',
      'Dubare Elephant Camp interaction ticket assistance',
      'Toll charges, state permits, parking fees, and driver charges',
    ],
    exclusions: [
      'Travel tickets to/from Bangalore or Mangalore',
      'Lunches, personal snacks, and beverages',
      'Elephant bathing or feeding tokens at Dubare',
      'Entry tickets at private adventure parks or monuments',
    ],
    importantInformation: [
      'Dubare Elephant Camp activities are conducted between 9:00 AM and 11:00 AM; morning departure is mandatory.',
      'Modest attire covering knees and shoulders is required at Namdroling Golden Temple.',
      'Best connected via Mangalore Airport (IXE) or Bangalore Kempegowda Airport (BLR).',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Kodagu & Abbey Falls Cascade',
        description: 'Arrive in the picturesque hills of Coorg. Check into your heritage planter\'s bungalow nestled in a working coffee estate. Later in the afternoon, take a nature walk down to Abbey Falls, roaring through lush hanging vines and nutmeg trees.',
        locations: ['Madikeri', 'Abbey Falls'],
        activities: ['Scenic Western Ghats foothills drive', 'Plantation check-in & freshly brewed estate coffee', 'Nature trail to Abbey Falls', 'Evening outdoor campfire with Kodava culinary delicacies'],
        meals: ['Dinner'],
        accommodation: 'The Coffee Bungalow Heritage Estate',
        travelInfo: 'Private transfer (~240 km from Bangalore or ~140 km from Mangalore)',
        images: ['https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80&auto=format'],
      },
      {
        day: 2,
        title: 'Dubare Elephant Sanctuary & Tibetan Heritage',
        description: 'Cross the sacred River Cauvery on a boat to reach the Dubare Elephant Camp. Witness the gentle giants being bathed and fed. Later, head to Bylakuppe to discover the Namdroling Monastery (Golden Temple), filled with Tibetan murals and serene chanting monks.',
        locations: ['Dubare Elephant Camp', 'Cauvery Nisargadhama', 'Bylakuppe Golden Temple'],
        activities: ['Dubare Elephant Camp visit & river crossing', 'Bamboo canopy walk at Nisargadhama island', 'Namdroling Tibetan monastery exploration', 'Tibetan flea market shopping & momos tasting'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'The Coffee Bungalow Heritage Estate',
        travelInfo: 'Private vehicle day tour (~80 km round-trip)',
        images: ['https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=800&q=80&auto=format'],
      },
      {
        day: 3,
        title: 'Plantation Discovery, Madikeri Fort & Sunset Vista',
        description: 'Spend your morning learning how Arabica and Robusta beans are cultivated, harvested, and roasted on an expert-led plantation walk. Visit the historic 17th-century Madikeri Fort and conclude your evening watching a dramatic sunset from the historic Raja\'s Seat.',
        locations: ['Estate Plantation', 'Madikeri Fort', 'Raja\'s Seat'],
        activities: ['Interactive coffee & spice trail with estate botanist', 'Historic Madikeri Fort & museum walk', 'Sunset views with fountain show at Raja\'s Seat'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'The Coffee Bungalow Heritage Estate',
        travelInfo: 'Local Madikeri circuit transfers',
      },
      {
        day: 4,
        title: 'Talacauvery Sacred Heights & Farewell',
        description: 'Drive up to Talacauvery at the summit of Brahmagiri Hills, the holy origin point of the Cauvery River. Take in sweeping views before commencing your return transfer.',
        locations: ['Bhagamandala', 'Talacauvery', 'Return Journey'],
        activities: ['Sacred shrine visit at Brahmagiri heights', 'Pure Coorg blossom honey & homemade wine tasting', 'Return drop-off transfer to airport or railway station'],
        meals: ['Breakfast'],
        travelInfo: 'Return cab transfer to Bangalore / Mangalore',
      },
    ],
  },
  'ooty-highlands': {
    nights: 2,
    shortDescription: 'Breathe in the crisp air of the Nilgiris as you journey through eucalyptus groves and vintage hill railways.',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80&auto=format',
    hotelIds: ['nilgiri-forest-resort'],
    vehicleIds: ['innova-crysta', 'tempo-traveller'],
    inclusions: [
      '2 Nights stay in a charming Nilgiri hill resort',
      'Daily breakfast and dinner at the resort restaurant',
      'Dedicated private vehicle for all Nilgiri mountain sightseeing',
      'Guided walk through Government Botanical Gardens',
      'Doddabetta Peak & Tea Factory visit assistance',
      'Driver allowances, parking, and toll fees',
    ],
    exclusions: [
      'Airfare / Train tickets to Coimbatore',
      'Lunches and personal shopping',
      'Optional horse riding, boating, or mountain train tickets',
    ],
    importantInformation: [
      'Nearest airport is Coimbatore International Airport (CJB) ~85 km.',
      'Single-use plastic bottles and plastic carrier bags are strictly prohibited in the Nilgiris.',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Climb the 36 Hairpin Bends & Botanical Exploration',
        description: 'Ascend through the scenic Nilgiri mountain passes into Ooty. Check in and visit the historic 55-acre Botanical Gardens and Ooty Lake.',
        locations: ['Coimbatore', 'Kallar Ghats', 'Ooty Botanical Gardens'],
        activities: ['Scenic ghat road mountain drive', 'Botanical garden exotic flora walk', 'Boating on Ooty Lake', 'Colonial heritage walk'],
        meals: ['Dinner'],
        accommodation: 'Nilgiri Forest Escape',
        travelInfo: 'Private transfer from Coimbatore (~85 km / 3 hours)',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&auto=format'],
      },
      {
        day: 2,
        title: 'Heritage Toy Train & Doddabetta Cloud Summit',
        description: 'Ride the iconic UNESCO Nilgiri Mountain Railway toy train through pine tunnels to Coonoor. Visit Sim\'s Park, Dolphin\'s Nose, and Doddabetta Peak.',
        locations: ['Coonoor', 'Sim\'s Park', 'Doddabetta Peak'],
        activities: ['Heritage toy train ride', 'Dolphin\'s Nose panoramic gorge view', 'Doddabetta summit telescope view', 'Artisan tea factory & chocolate tasting'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Nilgiri Forest Escape',
        travelInfo: 'Private sightseeing vehicle (~45 km circuit)',
      },
      {
        day: 3,
        title: 'Pykara Pine Forests & Coimbatore Descent',
        description: 'Walk among towering pines at Shooting Point and visit scenic Pykara Lake & Falls before descending back to Coimbatore.',
        locations: ['Pykara Lake', 'Pine Forest', 'Coimbatore'],
        activities: ['Pine forest walk', 'Speed-boating at Pykara', 'Nilgiri eucalyptus essential oil shopping', 'Return drop-off transfer'],
        meals: ['Breakfast'],
        travelInfo: 'Descent transfer to Coimbatore (~85 km)',
      },
    ],
  },
  'shimla-serenity': {
    nights: 4,
    shortDescription: 'Colonial charm meets Himalayan grandeur — a romantic journey through snow-dusted forests and heritage boulevards.',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80&auto=format',
    hotelIds: ['himalayan-boutique'],
    vehicleIds: ['innova-crysta', 'fortuner'],
    inclusions: [
      '4 Nights stay in a boutique Himalayan mountain resort',
      'Daily breakfast and four-course evening dinners',
      'Private luxury vehicle with experienced mountain driver',
      'Heritage Viceregal Lodge and Mall Road walking tour',
      'Excursion to Kufri slopes and nature park',
    ],
    exclusions: ['Airfare to Chandigarh / Delhi', 'Lunches and personal expenses', 'Ski equipment / pony rentals at Kufri'],
    importantInformation: ['Winter trips (Dec-Feb) require heavy woollens and thermal wear.', 'Chandigarh (IXC) is the closest major commercial airport ~120 km.'],
    itinerary: [
      {
        day: 1,
        title: 'Ascent to the Summer Capital of the Raj',
        description: 'Scenic climb from Chandigarh into Himachal Pradesh. Check in and take an evening walk on the iconic Ridge.',
        locations: ['Chandigarh', 'Shimla', 'The Ridge'],
        activities: ['Scenic Himalayan expressway drive', 'Resort check-in with apple cider welcome drink', 'Evening stroll along Mall Road and The Ridge'],
        meals: ['Dinner'],
        accommodation: 'Himalayan Nest Boutique',
      },
      {
        day: 2,
        title: 'Colonial Heritage & Jakhu Hanuman Temple',
        description: 'Explore the stately Viceregal Lodge and take the ropeway up to Jakhu Temple atop Shimla\'s highest point.',
        locations: ['Viceregal Lodge', 'Jakhu Hill', 'Christ Church'],
        activities: ['Viceregal Lodge architectural tour', 'Jakhu ropeway ride and giant Hanuman statue visit', 'Christ Church stained glass viewing'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Himalayan Nest Boutique',
      },
      {
        day: 3,
        title: 'Kufri Highland Slopes & Himalayan Nature Park',
        description: 'Excursion to Kufri for panoramic snow-peak vistas, cedar forest trails, and Himalayan wildlife.',
        locations: ['Kufri', 'Fagu Valley', 'Chini Bungalow'],
        activities: ['Kufri viewpoint adventure', 'Himalayan Monal & leopard spotting at Nature Park', 'Fagu apple orchard walk'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Himalayan Nest Boutique',
      },
      {
        day: 4,
        title: 'Mashobra Tranquility & Craignano Forest Trail',
        description: 'Discover peaceful Mashobra with its dense deodar groves, Craignano nature park, and pristine quietude.',
        locations: ['Mashobra', 'Craignano', 'Naldehra'],
        activities: ['Craignano apple blossom walk', 'Golf course meadow picnic at Naldehra', 'Bonfire evening with live acoustic music'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Himalayan Nest Boutique',
      },
      {
        day: 5,
        title: 'Scenic Himalayan Farewell',
        description: 'Relish a final mountain breakfast with sunrise views before your return transfer to Chandigarh.',
        locations: ['Shimla', 'Chandigarh Airport'],
        activities: ['Himachali handloom and honey shopping', 'Scenic descent drive to Chandigarh'],
        meals: ['Breakfast'],
      },
    ],
  },
  'darjeeling-dawn': {
    nights: 3,
    shortDescription: 'Watch Kanchenjunga glow gold at dawn, sip the world\'s finest tea, and ride the legendary toy train.',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80&auto=format',
    hotelIds: ['darjeeling-manor'],
    vehicleIds: ['innova-crysta'],
    inclusions: [
      '3 Nights stay in an iconic 5-star heritage manor',
      'Daily gourmet breakfast and chef-crafted dinner',
      'Private vehicle for all sunrise and sightseeing excursions',
      'Tiger Hill sunrise excursion with tea on arrival',
      'Himalayan Mountaineering Institute & Zoo entry pass',
    ],
    exclusions: ['Airfare to Bagdogra (IXB)', 'Lunches and personal gratuities', 'Joy ride toy train tickets'],
    importantInformation: ['Tiger Hill sunrise requires early 4:00 AM departure.', 'Bagdogra (IXB) is ~70 km / 3.5 hours mountain drive.'],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in the Queen of the Hills',
        description: 'Scenic climb through tea gardens into Darjeeling. Check into the heritage manor with Kanchenjunga views.',
        locations: ['Bagdogra', 'Kurseong', 'Darjeeling'],
        activities: ['Rohini zigzag mountain climb', 'Heritage manor welcome with Muscatel tea', 'Sunset viewing over Kanchenjunga from private balcony'],
        meals: ['Dinner'],
        accommodation: 'The Darjeeling Manor',
      },
      {
        day: 2,
        title: 'Tiger Hill Golden Dawn & Seven Points Tour',
        description: 'Experience the world-renowned sunrise over Mt. Kanchenjunga. Visit Batasia Loop, Ghoom Monastery, and HMI.',
        locations: ['Tiger Hill', 'Ghoom Monastery', 'Batasia Loop', 'HMI'],
        activities: ['Golden sunrise spectacle over Kanchenjunga', 'Batasia Loop war memorial and toy train spiral', 'Himalayan Mountaineering Institute visit & museum', 'Red Panda spotting at Padmaja Naidu Zoo'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'The Darjeeling Manor',
      },
      {
        day: 3,
        title: 'Happy Valley Tea Estate & Tibetan Self-Help Center',
        description: 'Immerse in the artisan craft of Champagne of Teas at Happy Valley and explore Tibetan handicraft weaving.',
        locations: ['Happy Valley Estate', 'Tibetan Refugee Center', 'Mall Road'],
        activities: ['First flush tea picking & tasting session', 'Handmade Tibetan carpet weaving observation', 'Chowrasta Mall evening stroll with bakeries'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'The Darjeeling Manor',
      },
      {
        day: 4,
        title: 'Farewell Descent to Bagdogra',
        description: 'Final breakfast overlooking the Eastern Himalayas before descending to Bagdogra Airport.',
        locations: ['Darjeeling', 'Mirik Lake', 'Bagdogra'],
        activities: ['Mirik Lake scenic photo stop', 'Finest Darjeeling tea shopping', 'Return airport transfer'],
        meals: ['Breakfast'],
      },
    ],
  },
  'manali-adventure': {
    nights: 5,
    shortDescription: 'From river rafting to snow treks — Manali delivers the ultimate mountain adventure for thrill seekers.',
    coverImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=1200&q=80&auto=format',
    hotelIds: ['manali-summit-lodge'],
    vehicleIds: ['fortuner', 'innova-crysta'],
    inclusions: [
      '5 Nights accommodation in a riverside alpine retreat',
      'Daily power-packed breakfast and mountain dinner',
      'Private 4x4 / SUV vehicle for high altitude passes',
      'Solang Valley adventure & Atal Tunnel excursion',
      'Old Manali cafe & heritage temples walk',
    ],
    exclusions: ['Airfare / Volvo tickets', 'Lunches and personal gear rentals', 'Paragliding and adventure sports fees'],
    importantInformation: ['Rohtang Pass permits are subject to NGT guidelines and Tuesday closure.', 'Warm thermals and hiking boots recommended.'],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Beas Valley',
        description: 'Arrive in Manali along the roaring Beas River. Check into your pine-surrounded lodge.',
        locations: ['Kullu Valley', 'Manali', 'Beas River'],
        activities: ['Scenic river valley drive', 'Lodge check-in by the river', 'Evening stroll in Old Manali quaint lanes'],
        meals: ['Dinner'],
        accommodation: 'Summit Ridge Lodge',
      },
      {
        day: 2,
        title: 'Solang Valley Thrills & Atal Tunnel to Sissu',
        description: 'Experience Solang Valley and cross the engineering marvel of Atal Tunnel into Lahaul\'s snowy landscape.',
        locations: ['Solang Valley', 'Atal Tunnel', 'Sissu Waterfall'],
        activities: ['Solang adventure viewpoints', 'Atal Tunnel mountain crossing', 'Sissu waterfall & Lahaul valley panorama'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Summit Ridge Lodge',
      },
      {
        day: 3,
        title: 'Hadimba Cedar Shrine & Vashisht Hot Springs',
        description: 'Visit the 500-year-old wooden Hadimba Temple in Dhungri forest and take a dip in natural sulphur springs at Vashisht.',
        locations: ['Hadimba Temple', 'Vashisht Village', 'Jogini Falls'],
        activities: ['Ancient cedar forest meditation', 'Natural hot sulphur spring dip', 'Trek to scenic Jogini Waterfalls'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Summit Ridge Lodge',
      },
      {
        day: 4,
        title: 'Rohtang Snow Point Excursion',
        description: 'Ascend to 13,058 ft Rohtang Pass for breathtaking 360-degree snow-clad Himalayan views.',
        locations: ['Marhi', 'Rohtang Pass'],
        activities: ['High altitude pass ascent', 'Snow point photography and glacier viewpoints', 'Scenic mountain roadside chai stop'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Summit Ridge Lodge',
      },
      {
        day: 5,
        title: 'Naggar Castle & River Rafting Day',
        description: 'Explore the medieval wood-and-stone Naggar Castle and Roerich art gallery, followed by optional white-water rafting in Kullu.',
        locations: ['Naggar Castle', 'Nicholas Roerich Gallery', 'Kullu Rafting Point'],
        activities: ['Naggar heritage castle exploration', 'Russian Himalayan art viewing', 'White-water river rafting thrill on River Beas'],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Summit Ridge Lodge',
      },
      {
        day: 6,
        title: 'Farewell Descent from the Valley of Gods',
        description: 'Enjoy a peaceful morning breakfast before commencing your journey home.',
        locations: ['Manali', 'Chandigarh / Bhuntar'],
        activities: ['Himalayan woollen shawl & apple jam shopping', 'Return departure transfer'],
        meals: ['Breakfast'],
      },
    ],
  },
}

export const seedPackages: Package[] = rawPackages.map(p => {
  const extra = packageDetails[p.id] || {}
  return {
    id: p.id,
    name: p.title,
    slug: p.id,
    destination: p.destination,
    duration: p.duration,
    price: p.price,
    priceNote: p.priceNote,
    category: p.category,
    tag: p.tag,
    description: p.description,
    image: p.image,
    highlights: p.highlights,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...extra,
  }
})

export const seedHotels: Hotel[] = rawStays.map(s => ({
  id: s.id,
  name: s.name,
  normalizedName: normalizeHotelName(s.name),
  slug: s.id,
  location: s.location,
  category: s.category,
  rating: s.rating,
  pricePerNight: s.pricePerNight,
  description: s.description,
  amenities: s.amenities,
  image: s.image,
  active: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}))

export const seedVehicles: Vehicle[] = rawVehicles.map((v, idx) => {
  // Give each vehicle an authentic number plate if not present
  const plates: Record<string, string> = {
    'innova-crysta': 'TN 01 AB 1234',
    'tempo-traveller': 'KL 07 CD 5678',
    'swift-dzire': 'KA 04 EF 9012',
    'fortuner': 'TN 43 GH 3456',
  }
  const plate = plates[v.id] || `TN 01 X ${1000 + idx}`
  return {
    id: v.id,
    name: v.name,
    numberPlate: plate,
    normalizedNumberPlate: normalizeNumberPlate(plate),
    type: v.type,
    capacity: v.capacity,
    luggage: v.luggage,
    driverAvailable: v.driverAvailable,
    localRoutes: v.localRoutes,
    flexiblePickup: v.flexiblePickup,
    idealFor: v.idealFor,
    priceNote: v.priceNote,
    features: v.features,
    image: v.image,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
})

export const seedCategories: Category[] = rawCategories.map((c, i) => ({
  id: c.id,
  title: c.title,
  slug: c.id,
  subtitle: c.subtitle,
  description: c.description,
  image: c.image,
  badge: c.badge,
  color: c.color,
  order: i + 1,
  active: true,
}))

export const seedExperiences: Experience[] = rawExperiences.map(e => ({
  id: e.id,
  title: e.title,
  subtitle: e.subtitle,
  description: e.description,
  image: e.image,
  duration: e.duration,
  difficulty: e.difficulty,
  location: e.location,
  icon: e.icon,
  highlights: e.highlights,
  active: true,
}))

export const seedTestimonials: Testimonial[] = rawTestimonials.map(t => ({
  id: t.id,
  name: t.name,
  trip: t.trip,
  location: t.location,
  rating: t.rating,
  review: t.review,
  avatar: t.avatar,
  initials: t.initials,
  active: true,
}))

export const seedKnowledge: ChatKnowledge[] = [
  {
    id: 'k-company',
    title: 'About Hills Tourism',
    category: 'company',
    content: 'Hills Tourism is an enquiry-led premium tourism brand established in 2018. We specialize in custom mountain getaways across Munnar, Coorg, Ooty, Shimla, Darjeeling, and Manali. Our team designs personalized itineraries with local expertise, vetted homestays/resorts, and dedicated mountain-experienced drivers.',
    keywords: ['about', 'company', 'history', 'who are you', 'trust', 'local experts'],
    active: true,
  },
  {
    id: 'k-enquiry-process',
    title: 'How Hills Tourism Booking & Enquiry Works',
    category: 'policy',
    content: 'Hills Tourism operates on a personalized enquiry model, NOT instant transactional online booking. Customers submit an enquiry detailing their preferred package, dates, group size, and stay/vehicle options. Our local mountain trip planners reach out within 2 hours with a bespoke itinerary and transparent quote. No upfront payment is taken on the website.',
    keywords: ['booking', 'enquiry', 'payment', 'how to book', 'pricing', 'deposit', 'policy'],
    active: true,
  },
  {
    id: 'k-contact',
    title: 'Hills Tourism Contact & Support',
    category: 'general',
    content: 'You can contact the Hills Tourism team via WhatsApp at +91 99990 00000 or email hello@hillstourism.com. Support hours are 9 AM to 9 PM, 7 days a week. During trips, clients have 24/7 on-call coordinator support.',
    keywords: ['contact', 'phone', 'whatsapp', 'email', 'support', 'help', 'emergency'],
    active: true,
  },
  {
    id: 'k-seasons',
    title: 'Best Times to Visit Hill Stations',
    category: 'faq',
    content: 'Munnar, Ooty, and Coorg are pleasant year-round with lush monsoons (June-Sept) and crisp winter weather (Oct-Feb). Manali and Shimla experience winter snow from December to February, and blooming springs from March to June.',
    keywords: ['best time', 'weather', 'season', 'when to visit', 'snow', 'monsoon'],
    active: true,
  },
]

export const seedSiteSettings: SiteSettings = {
  siteName: 'Hills Tourism',
  tagline: 'Discover the Hills Beyond the Ordinary',
  contactPhone: '+91 99990 00000',
  contactEmail: 'hello@hillstourism.com',
  whatsappNumber: '+919999000000',
  address: 'Hill Country, Nilgiris & Western Ghats, India',
  operationalHours: '9 AM – 9 PM IST (7 Days)',
  totalTravelersMetric: '2,500+',
  routesCountMetric: '120+',
  averageRatingMetric: '4.9',
}
